export enum BookingDayOff {
  DAY_OFF = 'DAY_OFF',
  OT = 'OT',
  WORKING_LATE = 'WORKING_LATE',
  WORKING_EARLY = 'WORKING_EARLY',
  REMOTE = 'REMOTE',
  GO_OUT = 'GO_OUT',
  PERSONAL_LEAVE = 'PERSONAL_LEAVE',
  COMPENSATORY_LEAVE = 'COMPENSATORY_LEAVE',
  UNPAID_LEAVE='UNPAID_LEAVE',
  KEEPING_FORGET='KEEPING_FORGET',
  EQUIPMENT='EQUIPMENT'
}
